version: '3.8'
services:
    regtech-ui:
        image: node:lts-slim
        command: sh -c "npm install && npm start"
        restart: always
        working_dir: /usr/app
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
